title: CekFintech.com
description: Penyelenggara Fintech Lending Berizin di OJK per 31 Mei 2024
show_downloads: false
google_analytics: G-MKQK789F6L
theme: jekyll-theme-primer

markdown: kramdown

github:
  is_project_page: false
  private: true
  
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
